---
dependency:
  name: galaxy
driver:
  name: vagrant

lint: |
  yamllint -c molecule/tests/yamllint.yml .
  ansible-lint -v .

vagrant:
  raw_config_args:
    #- "ssh.insert_key = false"
    - "vm.network 'forwarded_port', guest: 80, host: 8080"

platforms:
  - name: TTYUser-Centos7
    box: "bento/centos-7.9"
    memory: 4096
    ansible_groups:
      - group_1
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
    #instance_raw_config_args:
      #- "vm.provision: shell, inline: 'which python || sudo yum -y install python3'"
  - name: TTYUser-Centos8
    box: "bento/centos-8.3"
    interfaces:
      - network_name: private_network
        type: static
        ip: "192.168.233.145"
    options:
      append_platform_to_hostname: false
    raw_config_args:
      - "vm.network 'private_network', type: 'dhcp', auto_config: false"
  - name: TTYUser-Ubuntu18
    box: ubuntu/bionic64
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.233.146"
  - name: TTYUser-Ubuntu20
    box: "generic/ubuntu2004"
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.233.147"
  - name: TTYUser-Debian
    box: "generic/debian9"
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.233.148"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  #name: ansible
  name: testinfra
  lint:
    name: flake8
  options:
    sudo: true
    v: 1
  directory: ../tests

#additional_files_or_dirs:
  #    - ../path/to/test_1.py
  #    - ../path/to/test_2.py
  #    - ../path/to/directory/*

scenario:
  create_sequence:
    # - dependency # not configured yet.
    - create
    - prepare
  check_sequence:
    #- dependency # not configured yet.
    # - cleanup # not configured yet.
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    # - dependency # not configured yet.
    - create
    - prepare
    - converge
  destroy_sequence:
    #- dependency # not configured yet.
    #- cleanup # not configured yet.
    - destroy
  test_sequence:
    # - dependency # not configured yet.
    - lint
    #- cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect # not configured yet.
    - verify
    # - cleanup # not configured yet.
    - destroy
