---
dependency:
  name: galaxy
driver:
  name: docker

lint: |
  yamllint -c molecule/tests/yamllint.yml .
  ansible-lint -v .

platforms:
  - name: TTYUser-Centos7-systemd
    hostname: ttytest-c7
    image: "geerlingguy/docker-centos7-ansible:latest"
    privileged: true
    tty: true
    #tmpfs:
    #  - /run
    #  - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
  - name: TTYUser-Centos8-systemd
    hostname: ttytest-c8
    image: "geerlingguy/docker-centos8-ansible:latest"
    privileged: true
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
  - name: TTYUser-Ubuntu18-docker
    hostname: ttytest-u18
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    privileged: true
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
  - name: TTYUser-Ubuntu20-docker
    hostname: ttytest-u20
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    privileged: true
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
  #- name: TTYUser-Centos8-docker
  #  hostname: ttytest-c8
  #  image: "pycontribs/centos:8"
  #  command: ${MOLECULE_DOCKER_COMMAND:-""}
  #  privileged: false
  #  tty: true
  #  environment:
  #    container: docker
  #- name: TTYUser-origin-docker
  #  image: "pycontribs/centos:7"
  #  pre_build_image: true
  #  tty: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint: |
    yamllint -c molecule/tests/yamllint.yml .
    ansible-lint -v .
  #name: testinfra
  #lint:
  #  name: flake8
  #options:
  #  sudo: true
  #  v: 1
  #directory: ../tests

#additional_files_or_dirs:
  #    - ../path/to/test_1.py
  #    - ../path/to/test_2.py
  #    - ../path/to/directory/*

# Default scenario! Optional.
scenario:
  create_sequence:
    # - dependency # not configured yet.
    - create
    - prepare
  check_sequence:
    #- dependency # not configured yet.
    # - cleanup # not configured yet.
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    # - dependency # not configured yet.
    - create
    - prepare
    - converge
  destroy_sequence:
    #- dependency # not configured yet.
    #- cleanup # not configured yet.
    - destroy
  test_sequence:
    # - dependency # not configured yet.
    - lint
    #- cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect # not configured yet.
    - verify
    # - cleanup # not configured yet.
    - destroy
