---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
  - name: get service facts
    service_facts:

  - name: Run apt update
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Install OpenSSH-server
    package:
      name: openssh-server
      state: present

  - name: Make sure SSHD running
    service:
      name: "{{ (ansible_os_family == 'Debian') | ternary('ssh', 'sshd') }}"
      state: started
      enabled: yes
    when:
      - ansible_facts.services['dbus.service'].source is defined
      - ansible_facts.services['dbus.service'].source == "systemd"

  - name: update sshd conf
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication.*$'
      line: 'PasswordAuthentication yes'

  - name: Remove nologin
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /run/nologin
      - /etc/nologin
      - /var/run/nologin
