---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  become: true
  tasks:
    # We run the BATS tests from the localhost, since they are black box tests
    - name: "Run BATS tests for {{ ansible_hostname }}"
      shell: >
        SUT_IP={{ ansible_default_ipv4.address }}
        ../tests/libs/bats/bin/bats --tap {{ playbook_dir }}/../tests/test_bats.bats
      register: bats_test
      delegate_to: localhost
      changed_when: false

    # Continue with ansible tests
    - name: Get service facts
      service_facts:

    - name: Set ssh service name
      set_fact:
        ssh_service: "{{ (ansible_os_family == 'RedHat') | ternary\
          ('sshd.service', 'ssh.service') }}"

    - name: Verify with ansible asserts
      assert:
        that:
          - "{{ ansible_facts.services[ssh_service].state == 'running' }}"
        fail_msg: "SSH service is not running well"
        success_msg: "SSH service is running"

    - name: Try to login with SSH and check number of created users
      shell: >
        sshpass -p 'passwordTest' ssh captain@{{ ansible_default_ipv4.address }} \
        -C -o ControlMaster=auto -o ControlPersist=60s \
        -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
        cat /etc/passwd | grep -E '^captain|^bela' | wc -l
      register: newusers
      delegate_to: localhost
      changed_when: false

    - name: Verify with ansible assets
      assert:
        that:
          - newusers.stdout == "2"
        fail_msg: "Not all users have been created"
        success_msg: "All users have been created and able to login with SSH"
